### ISSUE TITLE
Transaction parser

### ISSUE THREAD

**Issue by HinsonSIDAN** [sidan-lab/whisky-archive#93]
## Objective
Develop new feature of systematically parsing transaction information from hex, enable offchain code unit testing

## Tasks
- [ ] Develop the backward transaction parser - getting the transaction hex and parsing back to rust object
- [ ] Develop the offchain code unit testing framework on top of the transaction parser, introducing a brand new developer experience on unit testing offchain code on Cardano
- [ ] Integrate the transaction parser to mesh

## Deliverable
- [ ] New features available with documentation available in published rust package in crates.io
- [ ] New features available with documentation available in mesh core package

## Steps
- [ ] Function planning. What class / struct to put in? What information can be parsed? As tx-in details will be lost in round trip, do cache from tx-building process or use a fetcher?
- [ ] Function implementation
- [ ] Basic unit testing functions planning
- [ ] Basic unit testing functions implementation
- [ ] Implement the same on mesh
