### ISSUE TITLE
Documentation + Mesh doc planning

### ISSUE THREAD

**Issue by HinsonSIDAN** [sidan-lab/whisky-archive#94]
## Objective
Provide full set of documentation, bringing the proposal result to the community

## Tasks
- [ ] Complete all inline documentation on user-facing APIs, with public hosting for easy referencing.
- [ ] Figure out a way to host documentation in a way of least duplication. Alternatives are: inline generated documentation, gitbook, github wiki, mesh website
- [ ] Hosting a community in both MeshJS & SIDAN Lab discord for feedback, question and communication
